services: 
  mariadb:
    build: ./requirements/mariadb  # Create the Docker image from the specified directory
    container_name: mariadb
    environment:  # Get the environment variables from the .env file for database initialization
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_CREDENTIALS}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    secrets:
      - credentials
      - db_password
      - db_root_password
    ports:
      - "3306:3306"  # Port to use for connecting to the database
    volumes:
      - mariadb_data:/var/lib/mysql  # Directory where database data is stored persistently, even if the container is removed
#    networks:
#      - inception
    restart: always

secrets:
  credentials:
    file: ${DB_USER_CREDENTIALS}
  db_password:
    file: ${DB_USER_PASSWORD}
  db_root_password:
    file: ${DB_ROOT_PASSWORD}

volumes:
  mariadb_data:

#setting up the wordpress container that will contain the php service
#  wordpress:
#    build: 
#      context: ./requirements/wordpress
#    container_name: wordpress
#    environment:
#      WORDPRESS_DB_HOST: ${DB_HOST}
#      WORDPRESS_DB_NAME: ${DB_NAME}             # Usa la variabile dal file .env
#      WORDPRESS_DB_USER: ${DB_USER}           # Usa la variabile dal file .env
#      WORDPRESS_DB_PASSWORD: ${DB_PASS}  
#    volumes:
#      - ./srcs/requirements/wordpress:/var/www/html
#    env_file:
#      - .env
#    networks:
#      - inception
#
##setting up the nginx service
#  nginx:
#    #buil the nginx image
#    build: 
#      context: ./requirements/nginx
#    container_name: nginx
#    ports:
#      - "8080:80"
#      #link the directory "./web:/var/www/html" to the container
#    depends_on:
#      - wordpress
#    volumes:
#      - ./srcs/requirements/wordpress:/var/www/html
#    networks:
#      - inception
##To have access to the container, type"http://127.0.0.1:8080/"
#
#networks:
#  inception:
#    driver: bridge